### ISSUE TITLE
In phenaki to output video_codebook_ids...

### ISSUE THREAD

**Issue by 9B8DY6** [lucidrains/phenaki-pytorch#18]
![image](https://user-images.githubusercontent.com/67573223/202970013-f5207d1b-5b69-439e-97a7-f6310eb82f48.png)
I got (batchsize, t x h x w, hidden dimension) shape of video_codebook_ids output from C-ViViT. But if video is made into 1 dimension like this, I don't think each temporal and spatial dimension is considered for transformer and vq. 

In paper figure, tokens are separated into each frame so I can not understand why the output of c-vivit shape is (batchsize, t*h*w, hidden dimension)....
![image](https://user-images.githubusercontent.com/67573223/202971369-ed9191cc-dcc0-4054-bb78-502114af81d0.png)

Thank you

**Comment by lucidrains** [comment]
@9B8DY6 i think it is space and time is factorized in the cvivit, but not in maskgit (although i think factorizing it in maskgit as well is worth trying)
