### ISSUE TITLE
how to run cvivit trainer or phenaki trainer

### ISSUE THREAD

**Issue by 9B8DY6** [lucidrains/phenaki-pytorch#20]
Could you explain how to run cvivit trainer.py or phenaki trainer.py?

**Comment by gmegh** [comment]
Hi @lucidrains ! I am also having trouble understanding how both trainer classes relate to the not trainer classes and how to called the trained ones when initializing the other ones.

in that sense, is the readme example code up to date?

thanks so muchh

**Comment by lucidrains** [comment]
@gmegh sorry, been busy with some medical stuff, but circling back to video this week to deal some more damage..

yup, i'll write up the examples today, still missing the token critic trainer as well, and will get that done

**Comment by lucidrains** [comment]
@gmegh i got the cvivit trainer example in the readme now if you'd like to try it out

there's still a few bells and whistles from vision transformers literature that i'd like to apply to cvivit for faster training, but i think you'll see some results even with the vanilla version

i'll add the phenaki and token critic trainers tomorrow

**Comment by lucidrains** [comment]
ok, was able to get unconditional images and video training working fine for `PhenakiTrainer`, similar to `CViViTTrainer`, but still need to wire up the logic for training with text

will need another day

**Comment by lucidrains** [comment]
@gmegh do you want to try? https://github.com/lucidrains/phenaki-pytorch#phenaki-trainer-wip should be in a better state by weekend's end

**Comment by gmegh** [comment]
I will try over the weekend! Sorry, I have been busy this week with research

**Comment by lucidrains** [comment]
@gmegh ok! take your time as it is not quite polished yet :sweat_smile:

**Comment by lucidrains** [comment]
@9B8DY6 let me know if https://github.com/lucidrains/phenaki-pytorch#phenaki-trainer helps!
