### ISSUE TITLE
There is error in ema

### ISSUE THREAD

**Issue by 9B8DY6** [lucidrains/phenaki-pytorch#21]
After one iteration of training, there is difference btw ema_vae.online_model.buffers. So, I got an error in ema_vae.update().
![image](https://user-images.githubusercontent.com/67573223/204279614-b95c89ec-830c-44d7-ae51-b7e9bc518d5e.png)
How can I solve it?

**Comment by lucidrains** [comment]
@9B8DY6 thank you for reporting this

there was an issue with some non-persistent buffers in the alibi positional embedding being moving averaged

should be fixed in the latest version!
