### ISSUE TITLE
model.buffer is EMPTY list in EMA get_buffers_iter function

### ISSUE THREAD

**Issue by 9B8DY6** [lucidrains/phenaki-pytorch#22]
![image](https://user-images.githubusercontent.com/67573223/204449912-91690e53-e8a0-42fd-b6a9-c19bcdff08ce.png)
With vscode debugging, I found that the buffer lists of both online_model and ema_model are all the empty in 1 iteration. Is this right? The model is c-vivit, not custom model. I am new to EMA so, I have difficulty understanding this code. Sorry for that!

**Comment by 9B8DY6** [comment]
@lucidrains Is EMA essential for phenaki? If not, I will remove it in my code.

**Comment by lucidrains** [comment]
@9B8DY6 yup, it is essential imo

for any generative networks, you typically want to have an exponential moving averaged version

**Comment by lucidrains** [comment]
@9B8DY6 it is not necessary, but a common practice to eek out slightly better results, if you can afford the extra resources

**Comment by lucidrains** [comment]
i would say, if you are resource constrained and doing small batch sizes, then you should have it turned on

**Comment by lucidrains** [comment]
@9B8DY6 https://github.com/lucidrains/phenaki-pytorch/commit/134b0a39ef3f7b438be7fbdd35c3f35ff9568972 try setting `use_ema = False` on the `CViViTTrainer` init method

in my experience though, you'll want to have this on for optimal results
