### ISSUE TITLE
I have a theoretical question about maskgit cross attention

### ISSUE THREAD

**Issue by 9B8DY6** [lucidrains/phenaki-pytorch#23]
In cvivit, you would train video clip with the fixed number of frames.
When training maskgit to do cross attention with text tokens, how did you cut(?) corresponding text tokens for the given frames?
Thank you!

**Comment by lucidrains** [comment]
@9B8DY6 they don't actually produce the entire video from one large prompt at once

they are basically generating one scene at a time, with the next scene conditioned on the last few frames of the previous scene

<img width="833" alt="Screen Shot 2022-12-01 at 8 12 59 AM" src="https://user-images.githubusercontent.com/108653/205103334-9bc69cec-ecd9-400b-b641-f68b7112bedc.png">

**Comment by lucidrains** [comment]
in other words, you are always cross attending from all the video tokens to the text, within a scene
