### ISSUE TITLE
What is out of index?

### ISSUE THREAD

**Issue by 9B8DY6** [lucidrains/phenaki-pytorch#25]
I got this error in `loss = F.cross_entropy(logits[mask_token_mask], x[mask_token_mask])`
Then I found out the error line 181 phenaki_pytorch.py
![image](https://user-images.githubusercontent.com/67573223/208379540-02507b29-5579-4183-a4f3-e105fbc3b6b7.png)
After pos emb(torch.arange(~)), I got all the tensors as torch.tensor.Object
And then the CUDA error occurs....
```
CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
How can I solve it?

**Comment by lucidrains** [comment]
@9B8DY6 you need to set a higher `max_seq_len` on your `MaskGit`

i added a more informative error message in 0.0.63! https://github.com/lucidrains/phenaki-pytorch/commit/e33bc7c39de740985a4c0c58a1b8b8bc325737b3
