### ISSUE TITLE
Compatibility issue with A100-80G with version 0.0.67

### ISSUE THREAD

**Issue by 1geek0** [lucidrains/phenaki-pytorch#28]
I'm not able to use the A100-80G GPU because the torch version with 0.0.67 is not compatible with the card.

I'm not sure what my previous version was, probably the one before 0.0.66.

Is there a plan to upgrade the torch version? Any workaround?

**Comment by lucidrains** [comment]
there shouldn't be a restriction on the pytorch version you can use, as long as it is greater than 1.6

**Comment by 1geek0** [comment]
I see. When I install phenaki-pytorch > 0.0.65, it overwrites my torch version to 1.11 for some reason. I got around this by reinstalling torch after phenaki

**Comment by lucidrains** [comment]
@1geek0 how is the training going? are you seeing any cool results? 😛
