### ISSUE TITLE
cannot reproduce

### ISSUE THREAD

**Issue by robotNo201** [lucidrains/phenaki-pytorch#38]
I really dont think this can be reproduced, 

RuntimeError: Error(s) in loading state_dict for CViViT:
	Missing key(s) in state_dict: "discr.attn_blocks.3.null_kv", "discr.attn_blocks.3.q_scale", "discr.attn_blocks.3.k_scale", "discr.attn_blocks.3.norm.gamma", "discr.attn_blocks.3.norm.beta", "discr.attn_blocks.3.context_norm.gamma", "discr.attn_blocks.3.context_norm.beta", "discr.attn_blocks.3.to_q.weight", "discr.attn_blocks.3.to_kv.weight", "discr.attn_blocks.3.to_out.weight". 
	Unexpected key(s) in state_dict: "discr.blocks.6.conv_res.weight", "discr.blocks.6.conv_res.bias", "discr.blocks.6.net.0.weight", "discr.blocks.6.net.0.bias", "discr.blocks.6.net.2.weight", "discr.blocks.6.net.2.bias", "discr.blocks.5.downsample.1.weight", "discr.blocks.5.downsample.1.bias". 
	size mismatch for discr.to_logits.3.weight: copying a param with shape torch.Size([1, 8192]) from checkpoint, the shape in current model is torch.Size([1, 16384]).

**Comment by robotNo201** [comment]
i use a simple video dataset, no problem with gpu and dataset, and i haven't changed anything on the source code.

**Comment by robotNo201** [comment]
Alright, nevermine, its my problem, I should never waste time on a nonreproducible project, and a github less than 1k stars

**Comment by LuthandoMaqondo** [comment]
> and this RuntimeError: CUDA error: device-side assert triggered CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. have tried many gpu on google colab, all failed

I experienced the problem and posted it, as an issue.

**Comment by robotNo201** [comment]
> > and this RuntimeError: CUDA error: device-side assert triggered CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. have tried many gpu on google colab, all failed
> 
> I experienced the problem and posted it, as an issue.

I tried many all GPU on google colab but none work, what the error means is just that the training dataset and label are not correct, but i check the dataset and the label, you know it are the three lines:
texts = [
    'a whale breaching from afar',
    'young girl blowing out candles on her birthday cake',
    'fireworks with blue and green sparkles'
]
also, the dataset is videos = torch.randn(3, 3, 17, 256, 128).cuda() # (batch, channels, frames, height, width)
mask = torch.ones((3, 17)).bool().cuda() # [optional] (batch, frames)
so i dont see any problem here because the sample size is 3

**Comment by robotNo201** [comment]
> > and this RuntimeError: CUDA error: device-side assert triggered CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. have tried many gpu on google colab, all failed
> 
> I experienced the problem and posted it, as an issue.

maybe we can work together to fix this error.

**Comment by LuthandoMaqondo** [comment]
Let's do it, can you share your fork or you or I can share mine: [luthando-contribution](https://github.com/LuthandoMaqondo/phenaki-pytorch/tree/luthando-contribution)
