### ISSUE TITLE
phenaki-pytorch package not found

### ISSUE THREAD

**Issue by minarainbow** [lucidrains/phenaki-pytorch#4]
$ pip install phenaki-pytorch 

Above command doesn't work as it is not found. Will it be  updated soon?

**Comment by lucidrains** [comment]
@minarainbow Hi Mina! Thanks for your interest

I've released 0.0.1 so you can play around with some of the modules, but until the wip flag is removed, it isn't ready yet

Should be done this week

**Comment by minarainbow** [comment]
Got it! Thank you so much!
