### ISSUE TITLE
c-vivit return_recons = True with use_vgg_and_gan = True

### ISSUE THREAD

**Issue by 9B8DY6** [lucidrains/phenaki-pytorch#6]
```
if return_recons:
    return loss, fmap
```
But there is no fmap

**Comment by lucidrains** [comment]
@9B8DY6 ohh yea, cvivit training should be ready end of today

wiring up the full training code this afternoon

**Comment by lucidrains** [comment]
in general, if you see "wip" tag on the title of my repositories, it isn't ready yet

**Comment by lucidrains** [comment]
@9B8DY6 yea this should be resolved https://github.com/lucidrains/phenaki-pytorch/commit/966ea4e41fb944758fefab175b6445861f65a1f7 , will get to the training code tomorrow or saturday
