### ISSUE TITLE
Some errors that appear on the training results

### ISSUE THREAD

**Issue by IxxdbxxI** [lucidrains/phenaki-pytorch#8]
#### This is one frame in entire_video
![random0](https://user-images.githubusercontent.com/82143592/199880493-76acc607-e223-40b4-a172-28c818199f5c.jpg)
#### This is  our results video

https://user-images.githubusercontent.com/82143592/199881206-6f9d285b-2d32-4dae-8a66-0d76577ec1e4.mp4

## Thanks a lot

**Comment by YangBigSir** [comment]
I also want to know why.

**Comment by lucidrains** [comment]
It is not done yet. please be patient and stop sending me emails

If there is a "wip" flag, it isn't done

**Comment by lucidrains** [comment]
It is not done yet

For any of my repositories, if there is an wip flag, it means "work is in progress"

**Comment by YangBigSir** [comment]
Got is. Thanks！
